### ISSUE TITLE
Add guidance for when and how to use PATCH ReST API

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/data-access#27]
Add API guidance for when and how to use PATCH in REST, give lots of examples.

Add to REST Overview (data-access/blob/main/docs/api-reference/restful/rest/index.md)

**Comment by digitaldiina** [comment]
Do we need more than what is in data-access\docs\netserver\web-services\endpoints\rest-webapi\index.md (added during NetServer reorg) ? If no, close this issue. If yes, please specify what is missing.

**Comment by digitaldiina** [comment]
Discussed with @SuperOfficeDevNet and concluded that it is OK to close.
