### ISSUE TITLE
Merge conceptual WebApi content

### ISSUE THREAD

**Issue by digitaldiina** [SuperOfficeDocs/data-access#28]
Currently, there is a migrated version in the web-api folder *not* shown and a raw version in api-reference/webapi *shown*.

Bring this content together in web-api and rename folder to webapi.

After PR is approved and merged, we need to update docfx.json to include this folder.

**Comment by digitaldiina** [comment]
![image](https://user-images.githubusercontent.com/23242792/120634412-82cdc400-c46b-11eb-889e-2c3378274158.png)

Cleanup done. Added folder to end of data-access toc. To make docfx happy, add the webapi folder and its images to the Json file.

**Comment by SuperOfficeDevNet** [comment]
Done
