### ISSUE TITLE
Feedback for POST Person

### ISSUE THREAD

**Issue by SuperDJ** [SuperOfficeDocs/data-access#44]
The `MandatoryContactOnPerson` setting referenced in the docs doesn't seem to exists. The closest thing I could find is 
![image](https://user-images.githubusercontent.com/6484766/124469129-43f89a00-dd9a-11eb-9ed5-5fbd695e21c8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/api-reference/restful/rest/Person/v1PersonEntity_PostPersonEntity.md/#L1)

**Comment by SuperDJ** [comment]
Perhaps it is the right setting. In the settings "Contact" appears to be used in other places as well instead of "Person" for example:
![image](https://user-images.githubusercontent.com/6484766/125035454-207f6900-e092-11eb-8eb2-e8987f294676.png)

Also when the setting is set to `yes`, I will get an error `contactid is required` when validating a person without a company/ contact.

**Comment by digitaldiina** [comment]
You can read more about the [terminology and context-sensitive labels](https://docs.superoffice.com/database/getting-started/so-view-of-the-world.html) in the database introduction.

**Comment by digitaldiina** [comment]
MandatoryContactOnPerson added in https://github.com/SuperOfficeDocs/superoffice-docs/issues/95
