### ISSUE TITLE
Feedback for downloads

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/data-access#48]
Something is off here as the navigator have the page.
![image](https://user-images.githubusercontent.com/22498774/127835370-cb34e64e-9af1-4f04-82db-6f9b20fa5507.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [undefined](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/assets/downloads.md/#L1)

**Comment by digitaldiina** [comment]
Solution: add a minimal toc.yml file to data-access/docs/assets **and** ensure that it is included in the appropriate docfx.json file

**Comment by digitaldiina** [comment]
![image](https://user-images.githubusercontent.com/23242792/127840231-7c97a20a-3e9d-4aef-9364-cc1c80de9682.png)

**Comment by digitaldiina** [comment]
FYI: I've updated docfx.json in build dev but not elsewhere.
