### ISSUE TITLE
Document restricted agents

### ISSUE THREAD

**Issue by acdavidh** [SuperOfficeDocs/data-access#58]
Documents which SuperOffice service agents are restricted in Online (UserAgent/etc)

**Comment by digitaldiina** [comment]
The following agents are not available in Online by default. Access must be requested specifically when an app is registered.

* CRMScriptAgent
* DatabaseTableAgent (listed as but should not be - see https://github.com/SuperOfficeDocs/superoffice-docs/issues/77 )
* EMailAgent
* ErpSyncAgent
* MessagingAgent
* ReplicationAgent
* UserAgent
* WebhookAgent
