### ISSUE TITLE
Legacy CS SOAP API not visible on docs

### ISSUE THREAD

**Issue by kronicz** [SuperOfficeDocs/data-access#59]
Should be possible to access documentation for legacy CS SOAP API

**Comment by SuperOfficeDevNet** [comment]
Isn't the [Service SOAP documentation](https://docs.superoffice.com/service/soap/overview.html) what you are referring to?

Docs are located here in the [service-soap](https://github.com/SuperOfficeDocs/data-access/tree/main/docs/service-soap) folder.

**Comment by kronicz** [comment]
Could not find any way of locating it on docs.superoffice.com. It was not listed anywhere logical.
