### ISSUE TITLE
Feedback for How to Search using Find Selections

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/data-access#76]
We need to mention that this requires Services88 like on the article https://community.superoffice.com/en/content/content/netserver-sdk/netserver-9.x/superoffice-find/
![image](https://user-images.githubusercontent.com/22498774/140076627-6d9a92b8-670f-4e58-bc22-63536debab47.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [selection_how_to_search](https://github.com/SuperOfficeDocs/data-access/blob/main/docs/netserver/search/find-selection/how-to-search.md/#L1)

**Comment by SuperOfficeDevNet** [comment]
Fixed, will be published by Friday.
