### ISSUE TITLE
Bad documentation v1TicketMessageEntity_SendTicketMessage

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/data-access#81]
As discussed on the [forums](https://community.superoffice.com/en/developer/forum/rooms/topic/netserver-api-group/web-services/send-sms-via-rest-api-ticketmessageidsend-method/?userToNotify=5821):

https://docs.superoffice.com/api/reference/restful/rest/TicketMessage/v1TicketMessageEntity_SendTicketMessage.html

Can not send SMS via TicketMessage.SendTicketMessage

**Comment by digitaldiina** [comment]
The current docs are based on version 10.0.2.

The model has been changed in 10.0.3 and the new SendTicketMessageSMS method added.

This issue fixes the generated API docs manually until 10.0.3 is available.
