### ISSUE TITLE
Pages need description

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/data-access#94]
For SEO, the following pages need a description:

- [ ] "https://docs.superoffice.com/api/reference/restful/rest/List_DocumentTemplate/v1DocumentTemplateList_GetDocumentTemplateEntity.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/EMail_Agent/v1EMailAgent_FindContactOrPersonByEmailName.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/Contact_Agent/index.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.AuthorizationUsernamePassword.html"
- [x] "https://docs.superoffice.com/api/reference/netserver/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/Find_Agent/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/Contact/v1ContactEntity_GetAll.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.Agents.UserAgent.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/Document/v1DocumentEntity_DeletePhysicalDocument.html"
- [x] "https://docs.superoffice.com/api/netserver/logging/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/Document/v1DocumentEntity_PostDocumentEntity.html"
- [ ] "https://docs.superoffice.com/api/netserver/archive-providers/reference/findcontact.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/EMail_Agent/index.html"
- [ ] "https://docs.superoffice.com/api/reference/crmscript/CRMScript.NetServer.NSProjectMember.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/Document_Agent/index.html"
- [x] "https://docs.superoffice.com/api/"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/Contact/v1ContactEntity_PostContactEntity.html"
- [ ] "https://docs.superoffice.com/api/webapi/rest/index.html" NA
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.AuthorizationImplicit.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.AuthorizationAccessToken.html"
- [x] "https://docs.superoffice.com/api/netserver/entities/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/Contact/index.html"
- [x] "https://docs.superoffice.com/api/index.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.AuthorizationUserToken.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.Agents.ArchiveAgent.html"
- [ ] "https://docs.superoffice.com/api/reference/webapi/SuperOffice.WebApi.AuthorizationSystemUserTicket.html"

**Comment by SuperOfficeDevNet** [comment]
Some of these are generated, so the generators will need to be able to handle null descriptions accordingly.

- [ ] Verify or fix category and sub-category page descriptions to ensure the descriptions are used at build time.

**Comment by digitaldiina** [comment]
Pages moved from https://github.com/SuperOfficeDocs/superoffice-docs/issues/185 👍 

- [ ] "https://docs.superoffice.com/api/netserver/config/index.html"
- [ ] "https://docs.superoffice.com/api/netserver/archive-providers/data-aggregation.html"
- [ ] "https://docs.superoffice.com/api/netserver/what-is-netserver.html"
- [ ] "https://docs.superoffice.com/api/netserver/archive-providers/reference/contactpersondynamicselectionv2.html"
- [ ] "https://docs.superoffice.com/api/netserver/webhooks/subscription.html"
- [ ] "https://docs.superoffice.com/api/netserver/web-services/endpoints/agents-webapi/index.html"
- [ ] "https://docs.superoffice.com/api/netserver/archive-providers/reference/appointmentdynamicselectionv2.html"
- [ ] "https://docs.superoffice.com/api/netserver/search/index.html"
- [ ] "https://docs.superoffice.com/api/netserver/web-services/index.html"
- [ ] "https://docs.superoffice.com/api/netserver/webhooks/security.html"
- [ ] "https://docs.superoffice.com/api/netserver/web-services/endpoints/http-headers.html"
- [ ] "https://docs.superoffice.com/api/netserver/webhooks/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/agent/index.html"
- [ ] "https://docs.superoffice.com/api/reference/restful/rest/index.html"
- [ ]  "https://docs.superoffice.com/authentication/index.html"
- [ ] "https://docs.superoffice.com/authentication/online/sign-in-user/auth-code-flow.html"
- [ ] "https://docs.superoffice.com/authentication/webapi/index.html"
- [ ] "https://docs.superoffice.com/authentication/online/sign-in-user/implicit-flow.html"
- [ ] "https://docs.superoffice.com/authentication/users-and-associates.html"
- [ ] "https://docs.superoffice.com/authentication/webapi/systemuserclient.html"
- [ ] "https://docs.superoffice.com/authentication/onsite/webapi/index.html"
- [ ] "https://docs.superoffice.com/authentication/webapi/iauthorization.html"
